In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv(r"C:\Users\Rosebee\Desktop\TechCrush1\Dataset\dirty_cafe_sales.csv")
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
data.shape

(10000, 8)

In [5]:
#overview of the columns

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [6]:
#checking for null value
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [7]:
data["Transaction Date"].value_counts()

Transaction Date
UNKNOWN       159
ERROR         142
2023-06-16     40
2023-02-06     40
2023-07-21     39
             ...
2023-04-27     15
2023-09-24     15
2023-07-22     14
2023-03-11     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [8]:
#replacing unknown and error as null values
data["Transaction Date"] = data["Transaction Date"].replace(["UNKNOWN", "ERROR"], pd.NA)

In [9]:
data["Transaction Date"].value_counts()

Transaction Date
2023-02-06    40
2023-06-16    40
2023-03-13    39
2023-07-21    39
2023-09-21    39
              ..
2023-04-27    15
2023-11-24    15
2023-03-11    14
2023-02-17    14
2023-07-22    14
Name: count, Length: 365, dtype: int64

In [10]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     460
dtype: int64

In [11]:
#drop null values in the transaction date column
data.dropna(subset = ["Transaction Date"], inplace=True)
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [12]:
data.shape

(9540, 8)

In [ ]:
#converting the date column to datetime data type
data["Transaction Date"] = pd.to_datetime(data["Transaction Date"])

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9225 non-null   object
 2   Quantity          9405 non-null   object
 3   Price Per Unit    9375 non-null   object
 4   Total Spent       9383 non-null   object
 5   Payment Method    7101 non-null   object
 6   Location          6422 non-null   object
 7   Transaction Date  9540 non-null   object
dtypes: object(8)
memory usage: 670.8+ KB

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9225 non-null   object
 2   Quantity          9405 non-null   object
 3   Price Per Unit    9375 non-null   object
 4   Total Spent       9383 non-null   object
 5   Payment Method    7101 non-null   object
 6   Location          6422 non-null   object
 7   Transaction Date  9540 non-null   object
dtypes: object(8)
memory usage: 670.8+ KB

In [16]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [17]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      329
ERROR        283
Name: count, dtype: int64

In [18]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [19]:
# Replace all the error with unknown
data["Item"] = data["Item"].replace({"ERROR":"UNKNOWN"})

In [20]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      612
Name: count, dtype: int64

In [21]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
dtype: int64

In [25]:
#fill the null values
data["Item"] = data["Item"].fillna("UNKNOWN")

In [26]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      927
Name: count, dtype: int64

In [24]:
data.isna().sum()

Transaction ID         0
Item                 315
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
Items                  0
dtype: int64

In [27]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Items
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,Coffee
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,Cake
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,Cookie
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,Salad
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,Coffee

In [28]:
data["Location"].value_counts()

Location
Takeaway    2889
In-store    2872
ERROR        341
UNKNOWN      320
Name: count, dtype: int64

In [29]:
#replace error with unknown
data["Location"] = data["Location"].replace({"ERROR":"UNKNOWN"})

In [30]:
data["Location"].value_counts()

Location
Takeaway    2889
In-store    2872
UNKNOWN      661
Name: count, dtype: int64

In [31]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location            3118
Transaction Date       0
Items                  0
dtype: int64

In [32]:
#fill null value with the most nost occuring category like mode
data["Location"] = data["Location"].fillna("UNKNOWN")

In [33]:
data["Location"].value_counts()

Location
UNKNOWN     3779
Takeaway    2889
In-store    2872
Name: count, dtype: int64

In [34]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Items
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,Coffee
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,Cake
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19,Cookie
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,Salad
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,Coffee

In [35]:
data["Payment Method"].value_counts()

Payment Method
Digital Wallet    2197
Credit Card       2170
Cash              2158
ERROR              296
UNKNOWN            280
Name: count, dtype: int64

In [37]:
#replace error with unknown
data["Payment Method"] = data["Payment Method"].replace({"ERROR":"UNKNOWN"})

In [38]:
data["Payment Method"].value_counts()

Payment Method
Digital Wallet    2197
Credit Card       2170
Cash              2158
UNKNOWN            576
Name: count, dtype: int64

In [39]:
data.isna().sum()

Transaction ID         0
Item                   0
Quantity             135
Price Per Unit       165
Total Spent          157
Payment Method      2439
Location               0
Transaction Date       0
Items                  0
dtype: int64

In [41]:
#fill the null values with unknown
data["Payment Method"] = data["Payment Method"].fillna("UNKNOWN")

In [42]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      165
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
Items                 0
dtype: int64

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9405 non-null   object
 3   Price Per Unit    9375 non-null   object
 4   Total Spent       9383 non-null   object
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   object
 8   Items             9540 non-null   object
dtypes: object(9)
memory usage: 745.3+ KB

In [45]:
data["Quantity"].value_counts()

Quantity
5          1914
2          1892
4          1774
3          1766
1          1740
UNKNOWN     160
ERROR       159
Name: count, dtype: int64

In [46]:
data["Quantity"] = data["Quantity"].replace({"UNKNOWN": 1, "ERROR":1})

In [47]:
data["Price Per Unit"].value_counts()

Price Per Unit
3.0        2319
4.0        2219
2.0        1185
5.0        1150
1.0        1088
1.5        1073
ERROR       186
UNKNOWN     155
Name: count, dtype: int64

In [48]:
#converting the column to numerical data type
data ["Quantity"] = pd.to_numeric(data["Quantity"], errors ="coerce")

data ["Price Per Unit"] = pd.to_numeric(data["Price Per Unit"], errors ="coerce")

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9405 non-null   float64
 3   Price Per Unit    9034 non-null   float64
 4   Total Spent       9383 non-null   object
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   object
 8   Items             9540 non-null   object
dtypes: float64(2), object(7)
memory usage: 745.3+ KB

In [50]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity            135
Price Per Unit      506
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
Items                 0
dtype: int64

In [51]:
#fill with mean
data ["Quantity"] = data["Quantity"].fillna(data["Quantity"].mean())

data ["Price Per Unit"] = data["Price Per Unit"].fillna(data["Price Per Unit"].mean())

In [52]:
data.isna().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent         157
Payment Method        0
Location              0
Transaction Date      0
Items                 0
dtype: int64

In [53]:
data["Total Spent"] = data["Quantity"] * data["Price Per Unit"]

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9540 non-null   object
 1   Item              9540 non-null   object
 2   Quantity          9540 non-null   float64
 3   Price Per Unit    9540 non-null   float64
 4   Total Spent       9540 non-null   float64
 5   Payment Method    9540 non-null   object
 6   Location          9540 non-null   object
 7   Transaction Date  9540 non-null   object
 8   Items             9540 non-null   object
dtypes: float64(3), object(6)
memory usage: 745.3+ KB

In [56]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Items               0
dtype: int64

In [57]:
#check for duplicates
data.duplicated().sum()

np.int64(0)

In [58]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Items
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,Coffee
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,Cake
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,Cookie
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,Salad
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,Coffee